celebrities = [
    {"name": "Cristiano Ronaldo", "follower_count": 630000000, "description": "Futbolista profesional", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 505000000, "description": "Futbolista profesional", "country": "Argentina"},
    {"name": "Neymar Jr", "follower_count": 220000000, "description": "Futbolista profesional", "country": "Brasil"},
    {"name": "Kylian Mbappé", "follower_count": 115000000, "description": "Futbolista profesional", "country": "Francia"},
    {"name": "David Beckham", "follower_count": 88000000, "description": "Exfutbolista", "country": "Reino Unido"},
    {"name": "Ronaldinho", "follower_count": 76000000, "description": "Exfutbolista", "country": "Brasil"},
    {"name": "Zlatan Ibrahimović", "follower_count": 62000000, "description": "Futbolista", "country": "Suecia"},
    {"name": "Sergio Ramos", "follower_count": 64000000, "description": "Futbolista", "country": "España"},
    {"name": "Luka Modrić", "follower_count": 37000000, "description": "Futbolista", "country": "Croacia"},
    {"name": "Erling Haaland", "follower_count": 35000000, "description": "Futbolista", "country": "Noruega"},
    {"name": "Taylor Swift", "follower_count": 285000000, "description": "Cantante", "country": "Estados Unidos"},
    {"name": "Ariana Grande", "follower_count": 375000000, "description": "Cantante y actriz", "country": "Estados Unidos"},
    {"name": "Selena Gomez", "follower_count": 430000000, "description": "Cantante y actriz", "country": "Estados Unidos"},
    {"name": "Beyoncé", "follower_count": 320000000, "description": "Cantante", "country": "Estados Unidos"},
    {"name": "Rihanna", "follower_count": 150000000, "description": "Cantante y empresaria", "country": "Barbados"},
    {"name": "Shakira", "follower_count": 90000000, "description": "Cantante", "country": "Colombia"},
    {"name": "Bad Bunny", "follower_count": 48000000, "description": "Cantante urbano", "country": "Puerto Rico"},
    {"name": "Karol G", "follower_count": 69000000, "description": "Cantante urbana", "country": "Colombia"},
    {"name": "J Balvin", "follower_count": 52000000, "description": "Cantante urbano", "country": "Colombia"},
    {"name": "Dua Lipa", "follower_count": 89000000, "description": "Cantante pop", "country": "Reino Unido"},
    {"name": "The Weeknd", "follower_count": 75000000, "description": "Cantante", "country": "Canadá"},
    {"name": "Drake", "follower_count": 145000000, "description": "Rapero", "country": "Canadá"},
    {"name": "Nicki Minaj", "follower_count": 230000000, "description": "Rapera", "country": "Estados Unidos"},
    {"name": "Billie Eilish", "follower_count": 110000000, "description": "Cantante", "country": "Estados Unidos"},
    {"name": "Miley Cyrus", "follower_count": 215000000, "description": "Cantante y actriz", "country": "Estados Unidos"},
    {"name": "Anitta", "follower_count": 65000000, "description": "Cantante", "country": "Brasil"},
    {"name": "Rosalía", "follower_count": 27000000, "description": "Cantante", "country": "España"},
    {"name": "Camila Cabello", "follower_count": 65000000, "description": "Cantante", "country": "Cuba"},
    {"name": "Ozuna", "follower_count": 70000000, "description": "Cantante urbano", "country": "Puerto Rico"},
    {"name": "Maluma", "follower_count": 64000000, "description": "Cantante", "country": "Colombia"},
    {"name": "Dwayne Johnson", "follower_count": 395000000, "description": "Actor", "country": "Estados Unidos"},
    {"name": "Leonardo DiCaprio", "follower_count": 60000000, "description": "Actor", "country": "Estados Unidos"},
    {"name": "Tom Holland", "follower_count": 68000000, "description": "Actor", "country": "Reino Unido"},
    {"name": "Will Smith", "follower_count": 65000000, "description": "Actor y rapero", "country": "Estados Unidos"},
    {"name": "Scarlett Johansson", "follower_count": 58000000, "description": "Actriz", "country": "Estados Unidos"},
    {"name": "Zendaya", "follower_count": 185000000, "description": "Actriz", "country": "Estados Unidos"},
    {"name": "Emma Watson", "follower_count": 74000000, "description": "Actriz", "country": "Reino Unido"},
    {"name": "Robert Downey Jr.", "follower_count": 56000000, "description": "Actor", "country": "Estados Unidos"},
    {"name": "Chris Hemsworth", "follower_count": 58000000, "description": "Actor", "country": "Australia"},
    {"name": "Gal Gadot", "follower_count": 108000000, "description": "Actriz", "country": "Israel"},
    {"name": "Kim Kardashian", "follower_count": 365000000, "description": "Influencer", "country": "Estados Unidos"},
    {"name": "Kylie Jenner", "follower_count": 400000000, "description": "Influencer", "country": "Estados Unidos"},
    {"name": "Khloé Kardashian", "follower_count": 310000000, "description": "Influencer", "country": "Estados Unidos"},
    {"name": "Kourtney Kardashian", "follower_count": 220000000, "description": "Influencer", "country": "Estados Unidos"},
    {"name": "Kendall Jenner", "follower_count": 290000000, "description": "Modelo", "country": "Estados Unidos"},
    {"name": "MrBeast", "follower_count": 60000000, "description": "YouTuber", "country": "Estados Unidos"},
    {"name": "Ibai Llanos", "follower_count": 11000000, "description": "Streamer", "country": "España"},
    {"name": "AuronPlay", "follower_count": 16000000, "description": "Streamer", "country": "España"},
    {"name": "El Rubius", "follower_count": 17000000, "description": "YouTuber", "country": "España"},
    {"name": "Pokimane", "follower_count": 6000000, "description": "Streamer", "country": "Canadá"},
    {"name": "Justin Bieber", "follower_count": 295000000, "description": "Cantante", "country": "Canadá"},
    {"name": "Bruno Mars", "follower_count": 43000000, "description": "Cantante", "country": "Estados Unidos"},
    {"name": "Ed Sheeran", "follower_count": 48000000, "description": "Cantante", "country": "Reino Unido"},
    {"name": "Adele", "follower_count": 56000000, "description": "Cantante", "country": "Reino Unido"},
    {"name": "Post Malone", "follower_count": 26000000, "description": "Cantante", "country": "Estados Unidos"}
]